---
# gmx-2020.2-cuda-10.2-SSE2
# gmx-2020.2-cuda-10.2-AVX2_256/Dockerfile .

name: Test
on: [push]
jobs:
  build:
    strategy:
      matrix:
        simd: ["gmx-2020.2-cuda-10.2-AVX_256",
               "gmx-2020.2-cuda-10.2-AVX_512",
               "gmx-2020.2-cuda-10.2-AVX2_256",
               "gmx-2020.2-cuda-10.2-SSE2",
              ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build -t "longr/gromacs-docker:${{matrix.simd}}" -f ${{matrix.simd}}/Dockerfile .

    - name: List containers
      run: docker ps
      
    - name: Docker Login
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

    - name: Docker Push
      run: docker push "longr/gromacs-docker:${{matrix.simd}}"


  combine:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build -t "longr/gromacs-docker:gmx-2020.2-cuda-10.2" -f Dockerfile .
      
    - name: Docker Login
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

    - name: Docker Push
      run: docker push "longr/gromacs-docker:gmx-2020.2-cuda-10.2"
